### PR TITLE
Add empty data error handling logic

### PR DESCRIPTION
**Pull request by jingyujzhang**

### CODE REVIEW

**Comment by iangow** [comment]
@Jessiezjy (CC @azakolyukina): This looks good. I think if you commit and push more code to your `master` branch it will appear here. I can then take a quick look and merge into my `master`.

**Comment by azakolyukina** [comment]
@Jessiezjy (CC @iangow)

Could you please also download `comp.sec_history` table to `comp`. Thanks!

**Comment by Jessiezjy** [comment]
@azakolyukina (CC @iangow) : comp.sec_history is not among the existing 21 tables in comp. I cannot create a new table there. Can you create sec_history first so I can update it?

**Comment by azakolyukina** [comment]
@Jessiezjy: you should be able to do it now. I have just tested.

**Comment by iangow** [comment]
@Jessiezjy You'd just need to edit the `update_comp.py` script to include this table along with the other tables that are there.

**Comment by Jessiezjy** [comment]
@iangow (CC @azakolyukina ): It's not that easy. The compiler report Attribute error. I looked into it, the output of func sas_to_pandas df['postgres_type'] didn't have the "timestamp" type the code needed. Instead, it only has "text", "float8" and "date" type. Is it normal? If it is, I can just catch and handle this error. If it is not, I will have to investigate deeper.

**Comment by iangow** [comment]
OK. For now, I just used the old Perl code:

```
igowmbp15:wrds_pg igow$ export PGHOST=aaz.chicagobooth.edu
igowmbp15:wrds_pg igow$ export PGDATABASE=postgres
igowmbp15:wrds_pg igow$ export WRDS_ID=iangow
igowmbp15:wrds_pg igow$ ./wrds_update.pl comp.sec_history
Updated comp.sec_history is available. Getting from WRDS.
Getting schema for comp.sec_history
NOTICE:  schema "comp" already exists, skipping
NOTICE:  table "sec_history" does not exist, skipping
Beginning file import at 15:23:55
Importing data into comp.sec_history.
COPY 158322
Result of system command: 0
Completed file import at 15:24:05
Last modified: 07/04/2017 21:42:55
```

@Jessiezjy I will create a new issue on GitHub for the problem with the Python code.

**Pull request merged**
